### ISSUE TITLE
Trigger Argo CD Deployment via API

### ISSUE THREAD

**Issue by varmoh** [buerokratt/CentOps#233]
**As a** platform engineer, 
**I want to** trigger an Argo CD deployment after values are stored or when `deployment` is initiated, 
**so that** client environments are deployed using the chosen manifests and secrets.

AC

- [ ] Backend sends a POST request to Argo CD API with necessary metadata.
- [ ] Argo CD successfully creates or syncs the application based on the manifest.
- [ ] Deployment status is logged and optionally returned to the frontend.
- [ ] Errors from Argo CD are handled and reported clearly.

**Comment by bohdanintro** [comment]
@varmoh Added short overview of a whole process, please take a look

#### Argo CD with HashiCorp Vault and Kubernetes 

This is a general overview how to use  Argo CD API securely:
- all secrets will be stored in the Hashicorp Vault
- need to create argo cd manifest for all apps
- no need to use packaged charts
- CentOps UI calls backend to deploy some app, where internally backend calls
  Argo CD API with Bearer token (generated and stored into Vault before), example:
```shell
curl -X POST -H "Authorization: Bearer <ARGOCD_TOKEN>" \
  https://argocd.example.com/api/v1/applications/myapp/sync
```
- During this `Argo CD Vault plugin` extracts all needed secrets from Vault and replaces secret's placeholders in the Chart
- After app will be deployed into the kubernetes cluster

#### ARGO CD Installation

```shell
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

####  ARGO CD Vault Plugin (AVP) Set up

```shell
kubectl -n argocd patch deployment argocd-repo-server \
  --type json -p '[{
    "op": "add",
    "path": "/spec/template/spec/containers/0/volumeMounts/-",
    "value": {
      "mountPath": "/home/argocd/cmp-server/plugins/argocd-vault-plugin",
      "name": "custom-tools"
    }
  }, {
    "op": "add",
    "path": "/spec/template/spec/volumes/-",
    "value": {
      "name": "custom-tools",
      "emptyDir": {}
    }
  }]'
```

```shell
kubectl -n argocd patch deployment argocd-repo-server --type=json -p='[
  {
    "op": "add",
    "path": "/spec/template/spec/initContainers",
    "value": [
      {
        "name": "copy-avp",
        "image": "ghcr.io/argoproj-labs/argocd-vault-plugin:v1.16.0",
        "command": [ "cp", "/usr/local/bin/argocd-vault-plugin", "/custom-tools/argocd-vault-plugin" ],
        "volumeMounts": [
          {
            "mountPath": "/custom-tools",
            "name": "custom-tools"
          }
        ]
      }
    ]
  }
]'
```

#### Configure Vault Access

Enable Kubernetes auth method in Vault

`vault auth enable kubernetes`

Configure Vault to trust your cluster

```shell
vault write auth/kubernetes/config \
  token_reviewer_jwt="$(kubectl get secret $(kubectl get serviceaccount default -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 -d)" \
  kubernetes_host="https://<kubernetes-api>" \
  kubernetes_ca_cert=@/path/to/ca.crt ```
```
Create Vault role

```shell
vault write auth/kubernetes/role/argocd \
  bound_service_account_names=argocd-repo-server \
  bound_service_account_namespaces=argocd \
  policies=myapp-policy \
 ```


#### Add argo cd deployment files

<ul>
  <li>gitops-repo/
    <ul>
      <li>helm-charts/
        <ul>
          <li>(charts)</li>
        </ul>
      </li>
      <li>argo-apps/ 
        <ul>
          <li>app.yaml</li>
          <li>app2.yaml</li>
          <li>app3.yaml</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1                          
  namespace: argocd                   
spec:
  project: default                    
  source:
    repoURL: https://github.com/org/gitops-repo   # GitHub repo containing Helm chart
    targetRevision: main              # Git branch, tag, or commit
    path: helm-charts/app1            # Path to the Helm chart (unpackaged.yaml files)
    plugin:
      name: argocd-vault-plugin       # Tells Argo CD to use the Vault Plugin for secrets
  destination:
    server: https://kubernetes.default.svc 
    namespace: app1 
```

#### Login to the Argo CD and extract API token:

```shell
argocd login <ARGO_SERVER> --username admin --password <PASSWORD>
argocd account generate-token
```

#### Call Argo CD API with token:
```shell
 curl -X POST -H "Authorization: Bearer <ARGO_TOKEN>" https://<ARGO_SERVER>/api/v1/applications/{app_name}/sync
  ```
payload options:
- `appNamespace` - Kubernetes target namespace 
- `revision` - Git branch, tag, or commit to deploy
- `prune` - Delete resources no longer in Git
- `dryRun` - Simulate deployment without changes
- `resources` - Specific Kubernetes resources to sync
- `strategy` - Sync behavior (apply, hook, etc.)
- `retryStrategy` - How to retry on failure
- `syncOptions` - Extra sync flags/options
- `project` - Argo CD project for the app
