### ISSUE TITLE
Create CRUD endpoints to manage client secrets

### ISSUE THREAD

**Issue by varmoh** [buerokratt/CentOps#252]
**AS A** archidect
**I WANT** to manage client secrets through a REST API
**SO THAT** I can securely create, read, update, and delete secrets associated with each client.

AC
Create the following endpionts:
- [ ] GET /centops/admin/clients/{clientId}/secrets -- lists all client secrets
- [ ] POST /centops/admin/clients/{clientId}/secrets -- creates a new client secret
- [ ] GET /centops/admin/clients/{clientId}/secrets/{id} -- get client secret
- [ ] PUT /centops/admin/clients/{clientId}/secrets/{id} -- update client secret
- [ ] DELETE /centops/admin/clients/{clientId}/secrets/{id} -- delete client secret

Fields for client data model:
- name (string)
- value (string)
- created_time (date string)
- version (number)

---
Related designs:
https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=6650-43184&t=HmjMXll1BtiFFeJf-11
https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=6960-49300&t=HmjMXll1BtiFFeJf-11
https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=6960-49678&t=HmjMXll1BtiFFeJf-11
https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=6682-50200&t=HmjMXll1BtiFFeJf-11

**Comment by varmoh** [comment]
To help visualize the Ruuter communication I asked @KlviG to help me with his.
```
data_to_db:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/some-endpoint"
    body:
      Id: ${Id}
      name: ${string}
      kubernetes_cluster_address: ${address}
      kubernetes_cluster_namespace: ${namespace}
      hashicorp_vault_token: ${token}
      authentication_certificate: ${cert}
      created_at: ${timestamp}
      updated_at: ${timestamp}
  result: data_to_db_status
  next: data_to_vault_check


data_to_vault_check:
  switch:
    - condition: ${data_to_db_status.response.body[0]?.value === 'true'}
      next: data_to_vault
  next: end



data_to_vault:
  call: http.post
  args:
    url: "[#VAULT]/some-endpoint"
    body:
      Id: ${Id}
      name: ${string}
      kubernetes_cluster_ip: ${address}
      kubernetes_cluster_namespace: ${namespace}
      hashicorp_vault_token: ${token}
      authentication_certificate: ${cert}
      created_at: ${timestamp}
      updated_at: ${timestamp}
  result: something_goes_here?
  next: end
```
